# Generated by Django 5.2.3 on 2025-06-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0002_alter_scholarship_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
