# Generated by Django 5.2 on 2025-06-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0003_alter_scholarship_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scholarship',
            name='application_process',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='contact_address',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='contact_website',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='location',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='tags',
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='deadline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='eligibility',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='provider',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
